version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simona
      MYSQL_DATABASE: blogdb
      MYSQL_USER: simona
      MYSQL_PASSWORD: simona
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: simonalan/blog-application:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:


